language: php

php:
  - '7.0'

before_script:
  - composer install
  - mkdir -p build/logs

script:
  - vendor/bin/grumphp run
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls